service: ecommerce-api-gateway

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}

  # Add logging with explicit log group management
  logs:
    restApi:
      accessLogging: true
      # Explicitly set log group retention
      retentionInDays: 14
  
  environment:
    USER_POOL_ID: ${env:USER_POOL_ID}
    USER_POOL_CLIENT_ID: ${env:USER_POOL_CLIENT_ID}
    USER_POOL_CLIENT_SECRET: ${env:USER_POOL_CLIENT_SECRET, ''}
    USERS_TABLE: ${env:USERS_TABLE}
    BIOMETRIC_TABLE: ${self:service}-biometric-${self:provider.stage}
    USER_PROFILES_TABLE: ${self:service}-profiles-${self:provider.stage}
    AWS_REGION_NAME: ${env:AWS_REGION_NAME, 'us-east-1'}
    NODE_ENV: ${opt:stage, 'dev'}

  # Security & Performance
  timeout: 29
  memorySize: 512
    
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - cognito-idp:*
          Resource: "*"
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: 
            - !GetAtt BiometricTable.Arn
            - !GetAtt UserProfilesTable.Arn
        - Effect: Allow 
          Action: 
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "*"
        - Effect: Allow
          Action:
            - rekognition:DetectFaces
            - rekognition:CompareFaces
          Resource: "*"

functions:
  # 🔐 Auth Service - All public authentication endpoints
  authService:
    handler: auth-service.handler
    timeout: 29
    memorySize: 512
    # Removed reservedConcurrency for development
    # reservedConcurrency: 20
    # Explicit log group configuration
    logRetentionInDays: 14
    events:
      - http:
          path: /auth/register
          method: POST
          cors:
            origin: "*"
            headers:
              - Content-Type
              - Authorization 
              - X-Requested-With
            allowCredentials: false
      - http:
          path: /auth/refresh_token
          method: POST
          cors: true
      - http:
          path: /auth/logout
          method: POST
          cors: true
      - http:
          path: /auth/logout_all
          method: POST 
          cors: true
      - http:
          path: /auth/login
          method: POST
          cors: true
      - http:
          path: /auth/confirm
          method: POST
          cors: true
      - http:
          path: /auth/resend_confirmation
          method: POST
          cors: true
      - http:
          path: /auth/forgot_password
          method: POST
          cors: true
      - http:
          path: /auth/reset_password
          method: POST
          cors: true
      - http:
          path: /auth/change_password
          method: POST
          cors: true
      - http:
          path: /auth/health
          method: GET
          cors: true
      - http:
          path: /auth/biometric/register
          method: POST
          cors: true
      - http:
          path: /auth/biometric/login
          method: POST
          cors: true
      - http:
          path: /auth/biometric/status
          method: GET
          cors: true
      - http:
          path: /auth/biometric/delete
          method: DELETE
          cors: true
      - http:
          path: /auth/biometric/face/register
          method: POST
          cors: true
      - http:
          path: /auth/biometric/face/login
          method: POST
          cors: true
      - http:
          path: /auth/biometric/webauthn/register
          method: POST
          cors: true
      - http:
          path: /auth/biometric/webauthn/login
          method: POST
          cors: true

  # 👤 User Service - Protected user management endpoints  
  userService:
    handler: user-service.handler
    timeout: 29
    memorySize: 256
    # Removed reservedConcurrency for development  
    # reservedConcurrency: 10
    # Explicit log group configuration
    logRetentionInDays: 14
    events:
      - http:
          path: /users/profile
          method: GET
          cors: true
      - http:
          path: /users/profile
          method: POST
          cors: true
      - http:
          path: /users/change-password
          method: POST
          cors: true
      - http:
          path: /users/health
          method: GET
          cors: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
    host: 0.0.0.0
    noAuth: true 
    noTimeout: true 

  # Api Gateway Configuration
  apiGateway:
    # Request validation 
    request:
      validateRequestBody: true 
      validateRequestParameters: true 

    # Throttling (Rate Limiting)
    throttle:
      rateLimit: 1000 # requests per second 
      burstLimit: 2000 # burst requests 

    # Binary Media types 
    binaryMediaTypes:
      - '*/*'

    # Minimum compression size 
    minimumCompressionSize: 1024

    # Api Gateway logs
    logs:
      level: INFO 
      dataTrace: true 
      executionLogging: true 

resources:
  Resources:
    # Explicit CloudWatch Log Groups with proper naming
    AuthServiceLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: /aws/lambda/${self:service}-${self:provider.stage}-authService
        RetentionInDays: 14

    UserServiceLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: /aws/lambda/${self:service}-${self:provider.stage}-userService
        RetentionInDays: 14

    BiometricTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-biometric-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: biometricType
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: biometricType
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        SSESpecification:
          SSEEnabled: true

    UserProfilesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-profiles-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true

  Outputs:
    BiometricTableName:
      Description: "DynamoDB table for biometric data"
      Value: !Ref BiometricTable
    UserProfilesTableName:
      Description: "DynamoDB table for user profiles"
      Value: !Ref UserProfilesTable
    ApiGatewayUrl:
      Description: "API Gateway URL"
      Value: !Sub 'https://${ApiGatewayRestApi}.execute-api.${self:provider.region}.amazonaws.com/${self:provider.stage}'